name: Sync Petstore to ReadMe

on:
  push:
    paths:
      - 'docs/swagger-petstore.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_PETSTORE_SECRET }}
          oas-file-path: "docs/swagger-petstore.yaml"
          api-version: "v1.0.0"
