name: Sync Petstore to ReadMe

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_PETSTORE_SECRET }}
          oas-file-path: './petstore.json'
          api-version: 'v1.0.0'
